### ISSUE TITLE
ResolveScreenName issue

### ISSUE THREAD

**Issue by l4npro** [yvasyliev/java-vk-bots-long-poll-api-examples#1]
[ResolveScreenNameExample.java](https://github.com/yvasyliev/java-vk-bots-long-poll-api-examples/blob/master/src/main/java/bot/longpoll/examples/utils/ResolveScreenNameExample.java) isn't working, it throws NullPointerException:

`
Exception in thread "main" java.lang.NullPointerException
	at com.google.gson.internal.$Gson$Preconditions.checkNotNull($Gson$Preconditions.java:39)
	at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:72)
	at com.google.gson.reflect.TypeToken.get(TypeToken.java:296)
	at com.google.gson.Gson.fromJson(Gson.java:930)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at api.longpoll.bots.converters.json.GsonConverter.convert(GsonConverter.java:24)
	at api.longpoll.bots.methods.VkApiMethod.execute(VkApiMethod.java:95)
	at net.l4npro.vk.ResolveScreenNameExample.resolveScreenName(ResolveScreenNameExample.java:20)
	at net.l4npro.vk.ResolveScreenNameExample.main(ResolveScreenNameExample.java:51)
`

**Comment by yvasyliev** [comment]
Fixed in version 2.1.1
