### ISSUE TITLE
Добавить новый тип вложения "Опрос".

### ISSUE THREAD

**Issue by l4npro** [yvasyliev/java-vk-bots-long-poll-api-examples#2]
Столкнулся с проблемой, что бот крашится из-за его отсутствия.

`Exception in thread "main" java.lang.NullPointerException
	at api.longpoll.bots.adapters.deserializers.AttachmentDeserializer.getType(AttachmentDeserializer.java:50)
	at api.longpoll.bots.adapters.deserializers.AttachmentDeserializer.deserialize(AttachmentDeserializer.java:43)
	at api.longpoll.bots.adapters.deserializers.AttachmentDeserializer.deserialize(AttachmentDeserializer.java:28)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)`

**Comment by yvasyliev** [comment]
Добавил класс `Poll` в версии `2.1.3`

**Comment by l4npro** [comment]
Новая ошибка:
 
`Caused by: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.friends[0]
	at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:242)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 45 more`

**Comment by yvasyliev** [comment]
Какое сообщение отправляете?

**Comment by l4npro** [comment]
Ответ на сообщение с опросом.

**Comment by l4npro** [comment]
Вот, нашёл. Отправляю сообщение с опросом (на который уже, видимо, отвечали, ибо пустой пересланный опрос ошибки не выдаёт) боту в личные сообщения, выдаёт ошибку
![image](https://user-images.githubusercontent.com/45311377/135769553-ab695dbb-3ff9-4411-aaee-3a3774443db1.png)

**Comment by yvasyliev** [comment]
Исправил в версии `2.1.4`
