### ISSUE TITLE
Синтаксическая ошибка JSON

### ISSUE THREAD

**Issue by l4npro** [yvasyliev/java-vk-bots-long-poll-api-examples#3]
Спустя продолжительное время работы бота (около 15-20 часов), вылезает подобная ошибка.

![image](https://user-images.githubusercontent.com/45311377/137039050-e04f3779-5c79-4e84-a406-053c7b0c74f4.png)

`
Exception in thread "main" com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

 at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:897)
 at com.google.gson.Gson.fromJson(Gson.java:932)
 at com.google.gson.Gson.fromJson(Gson.java:897)
 at com.google.gson.Gson.fromJson(Gson.java:846)
 at com.google.gson.Gson.fromJson(Gson.java:817)
 at api.longpoll.bots.converters.json.GsonConverter.convert(GsonConverter.java:24)
 at net.l4npro.vk.client.DefaultLongPollClient.tryHandle(DefaultLongPollClient.java:86)
 at net.l4npro.vk.client.DefaultLongPollClient.getEvents(DefaultLongPollClient.java:69)
 at api.longpoll.bots.BotsLongPoll.run(BotsLongPoll.java:62)
 at api.longpoll.bots.BotsLongPoll.run(BotsLongPoll.java:50)
`

**Comment by l4npro** [comment]
![image](https://user-images.githubusercontent.com/45311377/137290871-bd9460da-e13d-408b-9016-bbc05e1edf62.png)

**Comment by l4npro** [comment]
![image](https://user-images.githubusercontent.com/45311377/137293020-53f37fa4-074b-4eaf-8e06-ac22a45efc91.png)
